platform :ios, '14.1'
use_frameworks!

target 'iosApp' do
  pod 'KuiklyIOSRender', :podspec => '../shared/KuiklyIOSRender.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
    end
  end
end
